### ISSUE TITLE
Fix breadcrumb in CERB

### ISSUE THREAD

**Issue by lisafast** [gc-proto/covid-19-guidance#10]
@Anbrie @cfarquharson We need to link the proto pages you are working on right now ( http://test.canada.ca/covid-19-guidance/proto/0_archive-of-prev-content/cerb23-03-2020/cerb-cra/index.html) to a prototyped ESDC CERB page for testing. 

We are working on that ESDC page with ESDC. So when you get this, let us know, or fix the breadcrumb yourself on every CRA CERB page - it should link to: 

http://test.canada.ca/covid-19-guidance/proto/cerb/ei-cerb-application.html

**Comment by Anbrie** [comment]
http://test.canada.ca/covid-19-guidance/proto/0_archive-of-prev-content/cerb23-03-2020/cerb-cra/index.html

Anne Brierley

**Comment by lisafast** [comment]
@Anbrie  - you replied with the same link. I'm not sure what that means. Do you want US to edit the pages, or will YOU edit the breadcrumb on those pages?

**Comment by Anbrie** [comment]
You asked for the page we are working on right now. That is what I’m working on. Do you mean something else? Email wasn’t clear.

Anne Brierley
mobile: 613-219-3099

**Comment by lisafast** [comment]
Ah, sorry, I wasn't clear. I know which pages you are working on. What we need is to ALSO make a change to those pages. Please alert @LanaStewa once you have finished your work for the day, and we will make the changes to the breadcrumbs of your CERB pages.
