### ISSUE TITLE
P7 applications open

### ISSUE THREAD

**Issue by lbelmore-gc** [gc-proto/covid-19-guidance#112]
Updates to open P7 applications

Landing page 
- Update alert to "Applications for claim period 7 (August 30 to September 26) are now open"

Periods you can apply for - 
- Move period 7 from "Upcoming" to "Open"
- change Apply now to Yes

How to apply
- Change alert that appears when period 7 is chosen from drop down
"claim period for ... is open"

**Comment by LMElston** [comment]
Changes drafted and will be submitted to PubHub once the widget is published (Monday).
[Sep30_P7_changes.docx](https://github.com/gc-proto/covid-19-guidance/files/5285156/Sep30_P7_changes.docx)

**Comment by LMElston** [comment]
PubHub ticket submitted: [209145](https://pab-dgap-lse-esl.isvcs.net/pubhub/pub/cp/consultRequest.action?id=209145&l=en)
