### ISSUE TITLE
P8 content updates re. employees on leave calculation

### ISSUE THREAD

**Issue by lbelmore-gc** [gc-proto/covid-19-guidance#113]
Review content and determine content updates needed

Here is the latest of the furloughed employees -
https://www.canada.ca/en/department-finance/news/2020/09/government-provides-update-on-support-for-furloughed-employees-under-the-canada-emergency-wage-subsidy.html

**Comment by LMElston** [comment]
Drafting the changes to "How the subsidy is calculated" that would result from this announcement.

**Comment by LMElston** [comment]
Draft reviewed by David O. with no issues noted. Next step Lorraine et al.
[Howthesubsidyiscalculated_Oct 15.docx](https://github.com/gc-proto/covid-19-guidance/files/5387457/Howthesubsidyiscalculated_Oct.15.docx)

**Comment by lbelmore-gc** [comment]
@LMElston - is this one complete now that we published the extension updates on Friday?

**Comment by LMElston** [comment]
Yes! Closing.
