### ISSUE TITLE
Update "What the changes are" with new announcement info

### ISSUE THREAD

**Issue by LMElston** [gc-proto/covid-19-guidance#115]
When details of the extension are announced, this page will need to change to:

- add details of announced changes for affected periods (probably to new tab at top of page)
- remove emphasis on safe harbour and mentions of "maximizing" 
- remove "how much you can qualify for" content (or change to reflect new periods if possible)
- integrate later periods into examples and remove some period 5 and 6 examples
- remove old infographics/add new ones
- promote any content that may become more pertinent (such as how to change a past application)

[What the changes are_working copy.docx](https://github.com/gc-proto/covid-19-guidance/files/5313103/What.the.changes.are_working.copy.docx)

TBD which periods will be affected.

**Comment by LMElston** [comment]
I created a working version on GitHub (with no real content) to use as our playground: 
http://test.canada.ca/covid-19-guidance/proto/wage-subsidy2/cews-what-changes.html

**Comment by lbelmore-gc** [comment]
Thanks @LMElston. The updates to this page will really depend on what is involved in the extension.

I would also say we should discuss what is the purpose of this page - and if the title should be changed. Is it a summary of the changes? or an overview of the program

**Comment by LMElston** [comment]
I will propose some of these updates as part of the P8 update as well (removing some/most of the references to maximizing the benefit/safe harbour as well as some P5-6 examples). I'll update the doc/page once the P7 example fix is in place.

**Comment by LMElston** [comment]
Emailed proposed changes to Ken/David/Bob Oct. 13th

**Comment by LMElston** [comment]
Another news release is apparently coming out today--will edit link (and possibly text) accordingly before publishing the page.

**Comment by LMElston** [comment]
Changes have been reviewed by LPRAB. @lbelmore-gc let me know how I can support the next step of getting Lorraine et al to approve :)

**Comment by LMElston** [comment]
Closing this issue as interim changes have been published. Further changes will be included in issue #123
