### ISSUE TITLE
P8 (pre-royal assent) updates - Calculate your subsidy amount page

### ISSUE THREAD

**Issue by lbelmore-gc** [gc-proto/covid-19-guidance#118]
Updates for P8 needed to allow calculation (in advance of applications opening) to go live on Oct 21st - unless extension announcements come out and adjustments are needed.

- No spreadsheet or calculator changes required - expect rename spreadsheet from Period 7 to Period 7-8
- add period 8 to drop down list 
- updates months for baseline associated with P8

@Borges-Porteous - anything else needed for P8 as it stands??

**Comment by Borges-Porteous** [comment]
I don't think so - that second bullet for drop down list applied to both the spreadsheet and online site. 

Other than the change in rate multiplier, the other rules all seem to be consistent with Period 7, so that should be as-is.

**Comment by lbelmore-gc** [comment]
With this pre royal assent P8 update the other item to include is

**Comment by LMElston** [comment]
Just want to add this change here as we often forget it:
You can currently use the calculator for claim periods **1 to 7**. More periods will be added as they become available.

**Comment by LMElston** [comment]
Published and OK :)
