### ISSUE TITLE
P8 (post royal assent) calculator update 

### ISSUE THREAD

**Issue by lbelmore-gc** [gc-proto/covid-19-guidance#121]
Updated version of calculator and spreadsheet to include finalized changes:

Top up calculation - update to check and use the best rate between:
- current month
- previous month 
- 3 month average (now referred to as a safe harbour rule)

Update where required to flag the need to recalculate and amend applications 

Miguel's updates for this version are currently found at:
http://test.canada.ca/covid-19-guidance/proto/wage-subsidy2/how-much-2.html

**Comment by LMElston** [comment]
Closing this issue as the P8 calculator has now been published live.
