### ISSUE TITLE
P8 (pre-royal-assent) content updates (non-calculator)

### ISSUE THREAD

**Issue by LMElston** [gc-proto/covid-19-guidance#122]
Content updates for opening of P8:
- Landing page - Update announcement for P8 opening
- What the changes are - Maybe add P8 examples (if ready; otherwise wait for post-RA)
- Periods you can apply for - Move P8 into active
- How to apply - Add P8 to available and consider disclaimer alert

**Comment by LMElston** [comment]
Attaching the proposed changes except for the P8 examples (not yet received).
[Oct28_P8_changes.docx](https://github.com/gc-proto/covid-19-guidance/files/5404520/Oct28_P8_changes.docx)

@lbelmore-gc let me know if you see any issues here!

**Comment by lbelmore-gc** [comment]
Thanks @Laura May!

It looks good.  The only addition I didn't see would be on the How to apply page to also update the drop down alert 
to mark it as "open"

**Comment by LMElston** [comment]
No problem @lbelmore-gc 
It's in there--it is at the top of the second page. Are you ok with that alert text? And do you think it's a good idea?

Were you looking for the calculator page to be in with this set of updates as well?

**Comment by lbelmore-gc** [comment]
@LMElston - the alert is good. Let's send it to LPRAB and see if they are ok with it.

**Comment by LMElston** [comment]
Published and OK for now :)
