### ISSUE TITLE
How to apply page

### ISSUE THREAD

**Issue by lbelmore-gc** [gc-proto/covid-19-guidance#133]
Tracking for content requirements for How to apply page

http://test.canada.ca/covid-19-guidance/proto/rent-subsidy/how-apply.html

Items to be reviewed/updated:

-  review content on gathering info on 3 properties for the application - need to clarify language 

- This page currently contains both setup instructions and how to apply steps for each claim period. Mockup separating the setup instructions onto a new page (placed in nav calculate your subsidy page)

- Remove option to add Direct Deposit through banks (this will likely be added at a later date once available)

**Comment by tanyafowler** [comment]
Removed option to add DD through banks.
