### ISSUE TITLE
Periods you can apply for

### ISSUE THREAD

**Issue by lbelmore-gc** [gc-proto/covid-19-guidance#136]
Ticket for tracking Periods you can apply for page

Should be mainly the same content as CEWS page.
Other areas to note:

aligns with cews claim periods - do we want to include this??
deadlines to apply (180 days)

Align with CEWS updates to layout http://test.canada.ca/covid-19-guidance/proto/wage-subsidy2/cews-periods-apply.html 
- maybe post launch

**Comment by tanyafowler** [comment]
Updating the requirements for this issue:

Reformat the page to follow the CEWS format. The only feature on CEWS that we don't need for CERS at this time is the "In detail" expand. 

I've drafted a How claim periods work section to match CEWS. Waiting for one sentence from J-F - updating text about 180 day time limit.

I'll ask Sean to re-work the page after he's finished with the metadata.

**Comment by lbelmore-gc** [comment]
closing this one and will add a new ticket for updated layout changes
