### ISSUE TITLE
How the revenue drop and subsidy rate are calculated - page

### ISSUE THREAD

**Issue by lbelmore-gc** [gc-proto/covid-19-guidance#16]
Review of the "How the revenue drop and subsidy rate are calculated" page content edits updates

**Comment by LMElston** [comment]
[cid:image001.jpg@01D66741.E0517BE0]

Laura May

Digital Design and Production Directorate (DDPD) | Direction de la conception et de la production numériques (DCPN)
Telephone | Téléphone 416-523-1072

**Comment by LMElston** [comment]
Need to consider suggested changes from David O for incorporation into the page and send back for final review.

**Comment by Alireme** [comment]
Overall rate of CEWS = base rate + top up rate 
- green plus sign looks like a button and is inconsistent with the rest of the design on the page. Maybe "and" or "plus" in the grey circle so it looks like the "or" circle above it.
- The heading/label itself disappears a bit in the grey box when this is a pretty important part of the page

**Comment by Alireme** [comment]
"Top-up revenue drop and rate calculations" 
- This is a noun string https://plainlanguage.gov/guidelines/words/avoid-noun-strings/ 
- Maybe "Calculations for your basic rate and the top-up for your drop in revenue" or something similar? it's definitely longer but something more descriptive that breaks up the nouns would make this phrase more clear

**Comment by LMElston** [comment]
Received significant edits from David O and will tackle this page this morning.

**Comment by LMElston** [comment]
> Overall rate of CEWS = base rate + top up rate
> 
> green plus sign looks like a button and is inconsistent with the rest of the design on the page. Maybe "and" or "plus" in the grey circle so it looks like the "or" circle above it.
> The heading/label itself disappears a bit in the grey box when this is a pretty important part of the page


Added a separate h3 for linking purposes/clarity and made the panel heading h4. @cfarquharson the green plus sign change can be your call.

**Comment by LMElston** [comment]
> "Top-up revenue drop and rate calculations"
> 
> This is a noun string https://plainlanguage.gov/guidelines/words/avoid-noun-strings/
> Maybe "Calculations for your basic rate and the top-up for your drop in revenue" or something similar? it's definitely longer but something more descriptive that breaks up the nouns would make this phrase more clear

Edited. Hopefully slightly better; there is probably a better heading structure than what we currently have.

**Comment by LMElston** [comment]
> Received significant edits from David O (12:02am) and will tackle this page this morning.

Partly complete as of 12:51. Will be receiving math for examples soon so I can draft text for those. Need to incorporate feedback from Lorraine on this page as well.

**Comment by LMElston** [comment]
> Received significant edits from David O (12:02am) and will tackle this page this morning.
> 
> Partly complete as of 12:51. Will be receiving math for examples soon so I can draft text for those. Need to incorporate feedback from Lorraine on this page as well.

Lorraine's feedback incorporated

**Comment by LMElston** [comment]
@cfarquharson I added more to the table of contents on this page, which I think helps (will need to make sure the headings are nested correctly at some point). There is still an opportunity to remove some redundancy but this feels a little better.

Sent you the examples and a few edits.
