### ISSUE TITLE
28 day prorated monthly expenses

### ISSUE THREAD

**Issue by lbelmore-gc** [gc-proto/covid-19-guidance#169]
Need to clarify the amounts entered will be prorated for the 28 day claim period

- Rent:
- Rent will be prorated for the days that fall within the 28 day claim period
- Are your rent and any rental income for this location paid monthly?

Own 
- update sub text under the fields to: payment for one calendar month

- update text above to: If your expense payment periods don't align with the monthly or yearly options, choose the CERS period (28 days) option.

**Comment by tanyafowler** [comment]
This was published along with P2 changes on Monday November 30. Closing issue.
