### ISSUE TITLE
CEWS Online calculator

### ISSUE THREAD

**Issue by lbelmore-gc** [gc-proto/covid-19-guidance#18]
Summary of updates and fixes needed for the online calculator:

•	The overlay pop ups for the duplicated employees (2, 3, 4, etc.) do not work yet  
•	The  spreadsheet showing the appropriate one based on the period isn’t quite working (he is on it so it might be ready by the time Lorraine looks at it)
•	The calculator option disappears completely for P1 to 4 but we may need to adjust the text for the spreadsheet so it doesn’t seem like an option
•	Still doesn’t work yet on IE11 or Safari
•	Doesn’t have the send data below push down the fields in the step 2b summary areas (he’s working on that)

**Comment by Michel-Tremblay** [comment]
-  The overlay pop ups for the duplicated employees (2, 3, 4, etc.) do not work yet
    -    **this should be fixed as of this afternoon**
-  The spreadsheet showing the appropriate one based on the period isn’t quite working (he is on it so it might be ready by the time Lorraine looks at it)
    -   **should be fixed as of yesterday**
-   Doesn’t have the send data below push down the fields in the step 2b summary areas (he’s working on that)
    - **this should be done as of this afternoon**

**Comment by LMElston** [comment]
@Borges-Porteus Is the text from last night for the revenue drop summary show/hide based on the safe harbour rule in progress?

**Comment by Alireme** [comment]
The summary of revenue drop rates should have "Your overall CEWS rate (base rate + top up rate) for this claim period is ___%" should be at the end so that it displays more clearly as addition. Participants were looking for the bottom number to be their CEWS rate, not the first number.

**Comment by Christopher-O** [comment]
@LMElston  are you okay with moving that to the bottom?  Also @Borges-Porteous  there is a line that I believe you added that says "The rate is 75% because the period 1-4 rate is higher than your calculated overall rate (you qualified for the "safe harbour" rule)".  I assume that should hidden unless the calculations determine that the safe harbour rule applies correct?  Has that been sent to @Michel-Tremblay to bind to the script?

**Comment by Borges-Porteous** [comment]
> @LMElston are you okay with moving that to the bottom? Also @Borges-Porteous there is a line that I believe you added that says "The rate is 75% because the period 1-4 rate is higher than your calculated overall rate (you qualified for the "safe harbour" rule)". I assume that should hidden unless the calculations determine that the safe harbour rule applies correct? Has that been sent to @Michel-Tremblay to bind to the script?

It's bound to the script - I just forgot to put the 'hidden' class on it by default! Would be great if one of you could add that in while you're making another page, just add 'hidden' to anything with the class 'safe-harbour-show'

**Comment by Christopher-O** [comment]
@Borges-Porteous when I get a response from @LMElston I will go in and add that class.   Thanks for the update.

**Comment by Alireme** [comment]
When you open the online calculator and see "Note: This calculator does not save any data and if you leave or refresh this page you may need to enter the information again" should be under the "Use the calculator" heading, as this applies to the entirety of the calculator

**Comment by Christopher-O** [comment]
@Alireme it is at the very top, however it's in an expand hide (as I didn't think it was "required" information..unless it shows that users are heistant to even try it because they don't know if the information is kept.  Therefore that statement in the hidden online portion should be removed.   If you believe that the expand/hide summary should have a better label, please advise.

**Comment by Alireme** [comment]
@Christopher-O unless i'm working on an old version, all I see at the top is the privacy statement in the expand/hide? It does say that we're not retaining information but people may still expect that they won't have to worry too much about losing their work.

**Comment by Christopher-O** [comment]
@Alireme I have made a PR to move that content into the expand hide and amend the summary text.

**Comment by LMElston** [comment]
I will include this move in my text updates (in progress right now)

**Comment by Alireme** [comment]
"How to determine the pre-crisis pay amount" link could be "methods of calculating baseline pay" or "new pay period options for determining baseline pay" something more descriptive of the new content in the overlay which will encourage more people to engage with it.  This overlay had great information people were excited about, but they needed to be directed here because repeat applicants already knew how to determine the pre-crisis pay amount.

**Comment by Alireme** [comment]
Not a big deal at all, but currently when I navigate away from the calculate your subsidy page with data on the page, and then go back to the page everything is wiped clear except the claim period. It still says "Period 5:..." and then the Summary of Step 1 is present, but there is no claim period listed.

**Comment by Christopher-O** [comment]
> "How to determine the pre-crisis pay amount" link could be "methods of calculating baseline pay" or "new pay period options for determining baseline pay" something more descriptive of the new content in the overlay which will encourage more people to engage with it. This overlay had great information people were excited about, but they needed to be directed here because repeat applicants already knew how to determine the pre-crisis pay amount.

@Alireme on the how-much-mt.html page the link text was changed to "Decide which option to use for the pre-crisis pay" as recommended by @LMElston and @Borges-Porteous

**Comment by Christopher-O** [comment]
> Not a big deal at all, but currently when I navigate away from the calculate your subsidy page with data on the page, and then go back to the page everything is hidden except the claim period. It still says "Period 5:..." and then the Summary of Step 1 is present, but there is no claim period listed.

@Michel-Tremblay  I believe you are aware of this issue, unsure if it's something you were going to look at before Aug 11 or if it's a browser specific issue.

**Comment by LMElston** [comment]
I am re-editing to reflect “new” somehow

**Comment by LMElston** [comment]
@Borges-Porteous none of the rate amounts should be able to be negative (0% is the lowest). Currently I can calculate a negative amount for the three-month revenue drop at C2. I also broke it by entering very high numbers in the 2020 months (it told me the safe harbour rule would kick in). Maybe you're aware; wanted to flag

**Comment by Michel-Tremblay** [comment]
> 
> 
> > Not a big deal at all, but currently when I navigate away from the calculate your subsidy page with data on the page, and then go back to the page everything is hidden except the claim period. It still says "Period 5:..." and then the Summary of Step 1 is present, but there is no claim period listed.
> 
> @Michel-Tremblay I believe you are aware of this issue, unsure if it's something you were going to look at before Aug 11 or if it's a browser specific issue.

I am aware. It's typical functionality for all fields to be reset. I'm on Firefox and this seems to be a caching issue/feature. If I clear my cache and refresh (CTRL+F5) all the fields are reset to their defaults.

The labels to show the chosen claim period are rigged to update when the dropdown is changed. I would have to rig it up to do that on load as well if we want to just call this a 'feature'

**Comment by lbelmore-gc** [comment]
@Christopher-O @Michel-Tremblay @Borges-Porteous  - can you confirm that this one is completed?  Let's close it if it is done.

**Comment by Michel-Tremblay** [comment]
All tasks have been completed.
