### ISSUE TITLE
Supporting documents - validation from CRA

### ISSUE THREAD

**Issue by lbelmore-gc** [gc-proto/covid-19-guidance#182]
Review feedback from CVB (Brigitte email)

- update headings and clarify the reviews are CRA review 
- highlight supporting docs needed

- possibly add link or more info on how to apply "gather info" step

**Comment by tanyafowler** [comment]
Ready in preview (After you apply page). Documents were already listed on page, but within expand/hides. Removed accordions, moved Keep your records section to the top of the Review of your claim heading, changed Review heading to What to expect when CRA reviews your claim.

Ready for approval.
