### ISSUE TITLE
CEWS Registry link

### ISSUE THREAD

**Issue by lbelmore-gc** [gc-proto/covid-19-guidance#19]
CEWS registry links to be added 

On hold for now– likely happening during the week of 17 August.

**Comment by LMElston** [comment]
From old Trello card: Adding link to ITB application listing CEWS recipients from CEWS secondary navigation. Goals is to have this published by June 22 (per Claude on June 18).
Mock-up: http://test.canada.ca/covid-19-guidance/proto/wage-subsidy/how-much.html
