### ISSUE TITLE
Improving label for alternate baseline remuneration periods

### ISSUE THREAD

**Issue by Borges-Porteous** [gc-proto/covid-19-guidance#21]
Another label we need to change is the one for baseline pay field in the employee by employee fields.

As it says in the pop-up definition, it's either Jan 1 to Mar 15 2020 or Jul 1 to Dec 31, 2019 (for Period 5).

It might be as simple as labelling the pop-up link "Decide the baseline remuneration period to use". Or, if there's a way to do it, then even adding in the 2 period options as bullets or some such

**Comment by LMElston** [comment]
I think this was done? 

Average weekly baseline pre-crisis (baseline) pay 
How to determine the pre-crisis pay amount

**Comment by Borges-Porteous** [comment]
Nope, that was what was there during testing.
- the 'baseline' is repeated in the first line, which looks very weird
- the 'How to determine the pre-crisis pay amount' was not working - very few participants clicked it, and those that did exclaimed that they would have wanted to see that

My hypothesis is that a small label change to have an action verb first, such as "Decide" could help. Also indicating that there are options could help, so something like
- "Decide which option to use for the pre-crisis pay" might help?

Otherwise, we could go the full mile and actually display the options without the overlay... though it would be nice to avoid that.

**Comment by LMElston** [comment]
Ah ok! Thanks for the further explanation. I thought it just said "Baseline pay" during testing. 

I'm good with the text you proposed, and the first instance of baseline does need to removed from the first line (that was an error)

**Comment by Christopher-O** [comment]
I will update @Michel-Tremblay  page with the new text.  Just to confirm we are removing the duplicate "baseline" word and changing the hyperlink text to what @Borges-Porteous is proposing.

**Comment by LMElston** [comment]
@christopher-o yep!

**Comment by Christopher-O** [comment]
@LMElston done.  @Michel-Tremblay will merge the changes.

**Comment by Michel-Tremblay** [comment]
I've merged all changes that were assigned to me
