### ISSUE TITLE
icon creating invalid path error

### ISSUE THREAD

**Issue by Christopher-O** [gc-proto/covid-19-guidance#211]
@loogart  the Icon file you added to the path
proto/vaccines/prevention-risks/img/

is causing errors and not allowing our IT person make changes using their git (even to a different folder).

It gives an invalid path response. 

Could you look into why this might be? Perhaps it needs a file extension.  Thanks!

**Comment by loogart** [comment]
Hey @Christopher-O, i removed the `./ ` before the src path, let me know if this works.

**Comment by Michel-Tremblay** [comment]
![image](https://user-images.githubusercontent.com/11430547/101792930-454b3800-3ad3-11eb-93c6-bb7e22d17f61.png)

This is the error I'm stuck on.  When we look at the file in github, the file is 0bytes. https://github.com/gc-proto/covid-19-guidance/blob/master/proto/vaccines/prevention-risks/img/Icon%0D

Can you confirm there's no invalid characters in the filename? Git is showing that there's a question mark in the filename.

**Comment by loogart** [comment]
@Michel-Tremblay I just removed a hidden file that was somehow hiding in there. Let me know if it works.

**Comment by Michel-Tremblay** [comment]
@loogart, it's working now. Thanks for your help!
