### ISSUE TITLE
10% Wage Subsidy links

### ISSUE THREAD

**Issue by LMElston** [gc-proto/covid-19-guidance#22]
From Natasha P:
We launched the TWS content today therefore the CEWS content should point to its new landing pages.

CEWS pages with TWS mention (that I’m aware of)
https://www.canada.ca/en/revenue-agency/services/subsidy/emergency-wage-subsidy/cews-calculate-subsidy-amount.html _[NOTE from Laura May: this link should *only* appear in the overlay]_
https://www.canada.ca/fr/agence-revenu/services/subvention/subvention-salariale-urgence/ssuc-calculez-montant-subvention.html

TWS landing pages
https://www.canada.ca/en/revenue-agency/services/subsidy/temporary-wage-subsidy.html
https://www.canada.ca/fr/agence-revenu/services/subvention/subvention-salariale-temporaire.html

**Comment by cfarquharson** [comment]
I did it on the 'How the subsidy is calculated' page, but @Chris-O, can you do it on the calculator page?

**Comment by Christopher-O** [comment]
@cfarquharson I did a PR on @Michel-Tremblay 's page.  We will do all the edits on there via PR and then move it over to the main page once or twice a day as we fix/change things.
