### ISSUE TITLE
Revenue drop calculation broken on mobile

### ISSUE THREAD

**Issue by Borges-Porteous** [gc-proto/covid-19-guidance#31]
So on mobile (iphone, safari) the how-much-mt.html page does not calculate either for jan-feb or corresponding of 2019.

On how-much.html, it calculates for jan-feb baseline (calc-alt), but not corresponding month of 2019 (calc)

I wonder if this is a change I made earlier today? Is there something that's not supported on iphones? Not sure what it would be though, so I would be grateful for any help or insight you might have Michel.

@cfarquharson thanks for identifying!

**Comment by Michel-Tremblay** [comment]
i can remove my fix to allow formatting and we can test again. i'm really hoping that isnt it.

**Comment by Michel-Tremblay** [comment]
@Borges-Porteous I've pushed a commit to remove that fix. let me know if this fixes anything

**Comment by Michel-Tremblay** [comment]
Apparently Apple doesn't support Safari for Windows anymore, I can't really help debug this.

**Comment by Borges-Porteous** [comment]
Definitely works again now on my iphone. Maybe it was the comma fix...?

Sorry... I seem to have put you up to a task that was in vain...

**Comment by Borges-Porteous** [comment]
You do mean the comma/space formatting fix, right? Or was this another formatting code?

**Comment by Michel-Tremblay** [comment]
no, all i removed were the calls to my ```toUnformattedNumber()``` function

so it looks like safari/iphones have stricter requirements for this😞

**Comment by cfarquharson** [comment]
@Michel-Tremblay

One suggestion (for after safari/iphones...and ipads) are fixed.  If found this solution to force the number keyboard (instead of getting the alpha keyboard and then having to switch to numbers manually for even input).  Would be a nice UX piece to include.
  http://demos.danf.ca/iosnumpad/

**Comment by Christopher-O** [comment]
@cfarquharson on my iphone XR, the numeric keypad comes up when I focus on the inputs....that's in chrome though...I cannot access the page in safari due to firewall limitations.

**Comment by Michel-Tremblay** [comment]
Thanks @cfarquharson have you seen this work with commas (French format)?

the only thing that sticks out to me is that by the HTML specification, ```<input type="number">``` **strictly does not allow commas**

**Comment by Michel-Tremblay** [comment]
I've added type=number for the currency fields on how-much-mt.html. This allows us to defer some validation to WET4 and gives us this UX improvement.
