### ISSUE TITLE
Reflect changed application form lines c1 (value and text) and c2 (text) on the calculator and in the pages

### ISSUE THREAD

**Issue by LMElston** [gc-proto/covid-19-guidance#49]
The decision is for the employer to enter the “current” revenue drop (not the higher of the current and previous period). 

Line c1 - Revenue drop for the current period

Is your average revenue drop for the previous three months greater than 50%?

Line c2 – Average revenue drop for the previous three months

**Comment by Michel-Tremblay** [comment]
I understand the change for C1, but C2 is already the three month reduction.

**Comment by LMElston** [comment]
> I understand the change for C1, but C2 is already the three month reduction.
c2 is just a change to the label, not the field. No worries for you there!

**Comment by Michel-Tremblay** [comment]
Ahh, ok, sounds good! Is this to be applied to how-much.html before end of day?

**Comment by LMElston** [comment]
> Ahh, ok, sounds good!
> The change for C1 has been made to how-much-mt.html with a383776
> Is this to be applied to how-much.html before end of day?

I think we need to decide exactly how we want to lay it out before we apply it, because just changing the number that's displayed will be confusing for people (c1 + c2 no longer = c3 if the deeming rule applied). I think we might also need to pull out the prior rate and display that. But this requires a conversation first. It's going to be discussed at the calculator touchpoint (and @cfarquharson and @christopher-o will maybe want to talk about display options?)

**Comment by Christopher-O** [comment]
@LMElston I'm a bit behind as I did not participate in the meeting that spawned these changes so I will need a bit more context on exactly what needs to be added/why and then we can discuss possible hows.  I'm a bit lost as I'm seeing mixed messages from it being a simple label fix to displaying more values.  A phone meeting probably will be best.

**Comment by LMElston** [comment]
> @LMElston I'm a bit behind as I did not participate in the meeting that spawned these changes so I will need a bit more context on exactly what needs to be added/why and then we can discuss possible hows.  I'm a bit lost as I'm seeing mixed messages from it being a simple label fix to displaying more values.  A phone meeting probably will be best.

Agree. I added this issue to put it on the radar but did not intend for the coding to begin yet, I apologize that I contributed to the confusion. Lorraine wants to discuss the details, not sure if she meant at the 11:30 touchpoint or prior to that. Will advise.
