### ISSUE TITLE
Active/LWP employees need to be whole numbers

### ISSUE THREAD

**Issue by Christopher-O** [gc-proto/covid-19-guidance#58]
@Borges-Porteous @Michel-Tremblay the calculator outputs for the amount of active employees and leave with pay need to be rounded up to the nearest whole number (as the application does not count fractions).   It just needs to be rounded up at the very end so there is only ever one extra employee in a company.

**Comment by Michel-Tremblay** [comment]
Pushed an update this morning that sends the active/lwp employee values through ```Math.ceil()```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/ceil

**Comment by Christopher-O** [comment]
@Michel-Tremblay  thanks!  But it seems the function to push the data to step 2b no longer works now.

**Comment by Christopher-O** [comment]
issue resolved
