### ISSUE TITLE
Update to csv function for French comma possiblities in Firefox

### ISSUE THREAD

**Issue by Michel-Tremblay** [gc-proto/covid-19-guidance#67]
The current to csv function was made assuming we wouldn't have commas. Since the current functionality would allow commas **in french, in Firefox only**, i propose this small fix to be placed in English so that it is copied to the french page. Creating this as an issue because my -mt page has other changes that shouldn't be put into production yet.

https://github.com/gc-proto/covid-19-guidance/blob/2b00a2c7ef06b0ee0ca54003b6bde212dd071415/proto/wage-subsidy2/how-much-mt.html#L2750

The for loop on this line and the line that it controls should change to:
```js
for (var j = 0; j < cols.length; j++) {
     if (document.documentElement.lang == "fr") {
         var val = cols[j].innerText.replace(",", ".");
         val = val.replace(/,/g, ".")
         val = val.replace(/\s/g, "")
         row.push(val);
     } else {
        row.push(cols[j].innerText.replace(",", ""));
    }
}

**Comment by Christopher-O** [comment]
@Michel-Tremblay  Firefox throws an error if there is a comma in the fields to say it needs a proper number...is that not sufficient?

**Comment by Michel-Tremblay** [comment]
It's only Firefox that allows it when the page is set to French.

http://test.canada.ca/covid-19-guidance/proto/wage-subsidy2/how-much-mt-fr.html

**Comment by Christopher-O** [comment]
@Michel-Tremblay @Borges-Porteous actually it's a problem for all browsers as the table renders the data with the commas.  I just tried with chrome and I get the same error.

**Comment by Christopher-O** [comment]
@Michel-Tremblay was this fix implimented in the mt-fr page?  I just tried it out and the output is still not formatted correctly.

**Comment by Michel-Tremblay** [comment]
no i just opened this issue to bring this issue and the solution to your attention. it will need to be applied before publishing

**Comment by Christopher-O** [comment]
@Michel-Tremblay could you add the fix to your mt-fr page so I can test it out?

**Comment by Michel-Tremblay** [comment]
updated

**Comment by Christopher-O** [comment]
@Michel-Tremblay I also tried it on my -co.html file and it seems to be functioning now as needed.
