### ISSUE TITLE
Link text for payroll service providers on "Who can apply"

### ISSUE THREAD

**Issue by LMElston** [gc-proto/covid-19-guidance#72]
CPA had a comment that was echoed by others that this link text on "Who can apply" does not work for them:

"Even if you didn't have a payroll account on March 15, you may still qualify if ... **you used a payroll service provider who made remittances on your behalf**"

LPRAB will need to approve this change. A few suggestions were floated for fixing this but none approved.

Other suggestions, closer to the FAQ language (now that we've seen it) could be:
"... **a third party made remittances on your behalf**"
"... **you used a third party to administer your payroll**"

**Comment by LMElston** [comment]
Sent David and Ken new text suggestions for their input.

**Comment by LMElston** [comment]
LPRAB's suggested wording for parallel structure and greatest accuracy is:

Even if you didn’t have a payroll account on March 15, you may still qualify if:
Situation 1 
**another person or partnership** made remittances on your behalf

**Comment by tanyafowler** [comment]
Missed sending this to J-F for translation. Sent to Carmen since J-F is off today and tomorrow. When Carmen replies I'll send PubHub ticket.

**Comment by LMElston** [comment]
The new text has now been published.
