### ISSUE TITLE
New CEWS Calculator spreadsheet -- 14-day issue

### ISSUE THREAD

**Issue by lbelmore-gc** [gc-proto/covid-19-guidance#73]
Need to update spreadsheet and calculator based on the 14 day issue outlined bloew. 

Miguel and Michel to review and test out these changes.

Emails for context:
------------------------------------------------------------------------------------------
From: Tremblay, MichelT <MichelT.Tremblay@cra-arc.gc.ca> 
Sent: August 12, 2020 8:20 AM
To: Belmore, Lisa <Lisa.Belmore@cra-arc.gc.ca>; Borges-Porteous, Miguel <Miguel.Borges-Porteous@tbs-sct.gc.ca>
Cc: Fowler, Tanya <Tanya.Fowler@cra-arc.gc.ca>; Michaud, Louis <Louis.Michaud@cra-arc.gc.ca>; Oakes, Christopher <Christopher.Oakes@cra-arc.gc.ca>; Farquharson, Chad <Chad.Farquharson@cra-arc.gc.ca>
Subject: RE: New CEWS Calculator spreadsheet -- 14-day issue

There was no logic to check the period when determining the eligibility of the employee (getting paid $0 for two weeks straight)

I’m pushing an update for the calculator to my –mt page that will only count the employee as ineligible if they were paid $0 for two weeks straight AND the period is 1-4.

From: Belmore, Lisa <Lisa.Belmore@cra-arc.gc.ca> 
Sent: August 12, 2020 8:11 AM
To: Borges-Porteous, Miguel <Miguel.Borges-Porteous@tbs-sct.gc.ca>
Cc: Fowler, Tanya <Tanya.Fowler@cra-arc.gc.ca>; Michaud, Louis <Louis.Michaud@cra-arc.gc.ca>; Tremblay, MichelT <MichelT.Tremblay@cra-arc.gc.ca>; Oakes, Christopher <Christopher.Oakes@cra-arc.gc.ca>; Farquharson, Chad <Chad.Farquharson@cra-arc.gc.ca>
Subject: FW: New CEWS Calculator spreadsheet -- 14-day issue

Hey Miguel - Can you have a look at this issue with the spreadsheet described below. Let me know what you think.

@team – seems like the same issue happens with the calculator. Can anyone with full knowledge of the logic help here??

Thanks!
L

From: Naufal, Bob <Bob.Naufal@cra-arc.gc.ca> 
Sent: August 12, 2020 6:28 AM
To: Eisner, Denise <Denise.Eisner@cra-arc.gc.ca>; Mathews, Ken <Ken.Mathews@cra-arc.gc.ca>
Cc: Westbrook, Karen <Karen.Westbrook@cra-arc.gc.ca>; Belmore, Lisa <Lisa.Belmore@cra-arc.gc.ca>
Subject: RE: New CEWS Calculator spreadsheet -- 14-day issue

Categorization: Unclassified 
Good morning,

As Karen pointed out, pursuant to the July legislative amendments to the subsidy, effective July 5, 2020 (Period 5), the eligibility criteria no longer exclude employees that are without remuneration in respect of 14 or more consecutive days in an eligibility period.

There appears to be a glitch in the spreadsheet (as well as the online calculator) in that the calculations are still excluding employees without remuneration in respect of 14 or more days (such as in the example below). The 14-day validation may have carried over from the period 1-4 calculator/spreadsheet, and therefore, should be revised for Periods 5 onwards. 

Hope this makes sense. Good pick up Karen !!!!

Thanks,

Bob 
Bob Naufal
Manager
Financial Institutions Section
Income Tax Rulings Directorate  
Phone - (613) 612-5823
Bob.Naufal@cra-arc.gc.ca

**Comment by Michel-Tremblay** [comment]
an updated has just been published to preview to address this issue in the calculator.

**Comment by lbelmore-gc** [comment]
these fixes are now resolved. thanks guys!

Closing this ticket.
