### ISSUE TITLE
CEWS infographics - updated look

### ISSUE THREAD

**Issue by tanyafowler** [gc-proto/covid-19-guidance#76]
Adding issue for tracking, although it is already mostly resolved - preview links have been sent to Lorraine for review and approval.

Received updated infographics this afternoon. Created thumbnails for 4 files (2 each in EN and FR) then submitted PDFs and JPGs in PubHub ticket 206898:

http://lse-esl.ec.rc.gc.ca/pab-dgap/pubhub/pub/cp/consultRequest.action?id=206898

**Comment by lbelmore-gc** [comment]
New Infographics are now live

https://canada.ca/en/revenue-agency/services/subsidy/emergency-wage-subsidy/cews-what-changes.html  

https://canada.ca/fr/agence-revenu/services/subvention/subvention-salariale-urgence/ssuc-changement-apportes.html

closing this ticket.
