### ISSUE TITLE
Validation added to EI and CPP lines

### ISSUE THREAD

**Issue by lbelmore-gc** [gc-proto/covid-19-guidance#80]
ABSB is adding validation to the application form for the EI (Line D) and CPP (Line E) to prevent amounts claimed in those lines when no employees are reported as being on leave with pay (Line AA)

Aiming for a target deadline for this to be completed by Friday Sept 11th (on preview)
I will confirm this timing and send an update if it changes.

**Comment by Michel-Tremblay** [comment]
Just published an update for this: http://test.canada.ca/covid-19-guidance/proto/wage-subsidy2/how-much.html

The validation is triggered when the user clicks the button to send data to 2b, and when the input for employees on leave is changed manually.

**Comment by Christopher-O** [comment]
@Michel-Tremblay I don't know if we want to risk someone not using that feature and then still having the option to enter in values, granted the labels do allude that it's for employees on leave with pay.
   
Could it be done as either the trigger to send data to 2a or if they have 0 in the EE on leave with pay as an onblur event?

@lbelmore-gc how important is it that a user does not have any opportunity to enter any data in step 3 if no employees are on leave with pay?  If it's more of a nice to have, then I don't see much concern with going forth with the code that Michel implimented.  If they don't want to risk anybody having a chance to enter in those values, then we may have to look at a more restrictive event.

**Comment by Michel-Tremblay** [comment]
> 
> 
> Could it be done as either the trigger to send data to 2a or if they have 0 in the EE on leave with pay as an onblur event?

@Christopher-O, This is the current functionality 😃 sorry for the confusion

**Comment by Christopher-O** [comment]
@Michel-Tremblay yes sorry about that I deleted my comment and hoped you didn't see it as I re-read the message after the fact.

**Comment by lbelmore-gc** [comment]
This looks good. My only question is that these fields are marked as "required"  - maybe that could be removed since it may be confusing

**Comment by Christopher-O** [comment]
@lbelmore-gc  the 10% wage subsidy has the required field even though if you pick P5+.  I don't know if that was in any of the testing, so I cannot confirm if it's a hinderance or not.  

Technically the fields are still required as they need to be entered (amount being 0.00) so I don't see it being a huge hinderance.  I will leave it to @Michel-Tremblay to determine if it would be quick to amend the script so the hidden class to those three "required" span elements if the inputs are readonly.

**Comment by Michel-Tremblay** [comment]
I can remove the text "(required)" and remove the required attribute from the inputs, but the red * is a pseudo element generated by WET4 on initialization. I would have to reinitialize WET4 in order to remove those, then reinitialize again if the state of this changes.

**Comment by Christopher-O** [comment]
@Michel-Tremblay I think simply hidding the required part of the label is sufficient.  The values are still "required" because there  has to be a value to calculate (even if it's 0).  For the application the user still needs to put $0 (for CPP), it will just give a validation error if they don't record any leave with pay employees.

**Comment by lbelmore-gc** [comment]
This looks good. My only question is should the content be the same as what they are using on the application? Here is what they sent in the email:
@tanyafowler @LMElston - can you have a look?

For consistency, can the online calculator and spreadsheet be updated as follows: 

For Periods 5 and higher, return an error message above Line D (or Line E, as applicable) if:
•	Line AA = 0, and,
•	Line D (or Line E) > $0.00

For reference, the Web form application will display the following error message to the user:  
Error: Line D and Line E must be $0 if Line AA (Number of eligible employees on leave with pay) is 0. 
For more information, see Active employees and employees on leave with pay. (Ref. code: 839)

Erreur : Les lignes D et E doivent être de 0 $ si la ligne AA (nombre d’employés admissibles en congé payé) est de 0.
Pour en savoir plus, lisez Employés actifs et employés en congé payé. (Code de réf. : 839)




![image](https://user-images.githubusercontent.com/68651474/92724594-e7bf1800-f338-11ea-9da3-79127ecce9b1.png)

**Comment by LMElston** [comment]
I don't think the error text needs to be the same. We make the line numbers/titles match because people need to manually transfer those numbers from the calculator to the application--error messages don't need this consistency.

That said, if we want to give people an opportunity to see/correct the problem, it might be helpful to add a line reference? e.g. "You have no employees on leave with pay (line AA) during this claim period".

**Comment by Michel-Tremblay** [comment]
I added this as placeholder text. I believe @Christopher-O was intending on updating it.

**Comment by lbelmore-gc** [comment]
Ok. great. @LMElston @tanyafowler - I'll leave it to you to provide the text for these.

**Comment by Christopher-O** [comment]
@lbelmore-gc @LMElston @Michel-Tremblay validation label has been updated to @LMElston suggestion.

**Comment by tanyafowler** [comment]
Validation text has been drafted in GitHub:

"You have no employees on leave with pay (line AA) during this claim period."

Added to:

- **Total EI and QPIP premiums that you paid on salary to eligible employees on leave with pay (for the claim period)**
- **Total CPP and QPP contributions that you made on salary to eligible employees on leave with pay (for the claim period)**

Sending to J-F for translation.

**Comment by tanyafowler** [comment]
French message:

"Vous n'avez pas d'employés en congé payé (ligne AA) pendant cette période de demande."

**Comment by tanyafowler** [comment]
PubHub ticket # 208367 completed today - these changes are now live. Closing issue.
