### ISSUE TITLE
New employees - clarify eligibility

### ISSUE THREAD

**Issue by lbelmore-gc** [gc-proto/covid-19-guidance#85]
**Which of your employees qualify page** 

UX testing showed it was unclear whether new employees qualify to be claimed under the CEWS

Solution - to add blurb about new employees, enter 0 to Which of your employees qualify page 

Are there other pages that need this content?

**Comment by LMElston** [comment]
My feeling is that the main point of need for this information is when people get to the 'pre-crisis pay' information on either the Which of your employees qualify page or in the calculator ("what do I do if this person wasn't working for me then??". Fortunately the calculator pop-up draws from the Which of your employees qualify content so it can be in both places at once.

I have drafted a sentence to add to this area that I hope will address the majority of people who need the information. It also bolds "new eligible employees" which should help a little if scanning:
[Which employees qualify - new employees.docx](https://github.com/gc-proto/covid-19-guidance/files/5211168/Which.employees.qualify.-.new.employees.docx)

If it's warranted, we can add a new heading/section for this information, but it's not my preferred choice given the amount of content already on the page. I am hoping most people will assume new employees can qualify and can ctrl+F for this if they're unclear. Other options are always welcome though!

**Comment by tanyafowler** [comment]
Sent document to Ken and David for review and feedback, along with P7 math example.
