### ISSUE TITLE
Adding employee name

### ISSUE THREAD

**Issue by lbelmore-gc** [gc-proto/covid-19-guidance#86]
UX research showed users are looking to assign names to the employee lines to help track and complete the data.

Users cannot personalize employees, they currently need reference sheet to determine which employee is which.

Add in field for employee name or alias (with messaging about privacy)

Add input field to personalize employees (instead of employee 1, employee 2, etc.)
Names will be editable and not mandatory

**Comment by Christopher-O** [comment]
@lbelmore-gc  the input field has been added and @Michel-Tremblay has added the script to change the name in the summary from Employee X to the name entered (and back to Employee X if the name is removed), as well as the full employee table summary.   Please confirm that all criteria has been met and issue can be closed.

**Comment by tanyafowler** [comment]
@Michel-Tremblay @Christopher-O Can one of you outline the code changes so I can include it in the ticket instructions Mathieu will be working on? Thanks :)

**Comment by Christopher-O** [comment]
I will defer first to @Michel-Tremblay to send the code as I would only be able to send the HTML and not the Javascript/JQuery.  However if needed, I can provide at least the HTML code.

**Comment by Christopher-O** [comment]
@tanyafowler no problem.  @Michel-Tremblay will still need to provide the JS code snippet to make it work though.
