### ISSUE TITLE
calculator options - text for 20 employee cap

### ISSUE THREAD

**Issue by lbelmore-gc** [gc-proto/covid-19-guidance#87]
UX testing showed there was confusion about 20 employees cap when choosing the calculator vs the spreadsheet

Solution - Remove reference statement to 20 employees or less  in calculator option and large group of employees in spreadsheet option

**Comment by Christopher-O** [comment]
List item for both the online calculator and the spreadsheet have been removed.  @LMElston  please record change when porting to preview.   Closing issue.

**Comment by lbelmore-gc** [comment]
@Christopher-O - let's reopen this one and I'll add it to the ready for approvals list

**Comment by lbelmore-gc** [comment]
adding a screen shot of new text

![image](https://user-images.githubusercontent.com/68651474/92653184-fadfd280-f2bb-11ea-80eb-90cae7683bef.png)

**Comment by tanyafowler** [comment]
Part of PubHub ticket 208575 - assigned to Mathieu.
