### ISSUE TITLE
Checklist updates to display and/or 

### ISSUE THREAD

**Issue by lbelmore-gc** [gc-proto/covid-19-guidance#88]
Before you start checklist. Secondary items under the split and/or on the checklist were not always read

Separate "and" items into individual checkboxes and put "or" objects in split (6/6) grid...or at very least further emphasize the "and" and "or" phrases (with font awesome circle icon) 5-9 listed as first option instead of 1-4

**Comment by Christopher-O** [comment]
For the "and" items, because they are basically two part steps of the same task, it might be a bit more problematic with user understanding to seperate them into seperate checklists (tasks).   My proposal would be to mimic the "or" statements with the phrase "Both of the following apply:" or "All of the following apply:" as a lead in.  Thoughts?

**Comment by Christopher-O** [comment]
@lbelmore-gc @LMElston I have updated the checklist items for the calculate page.  After testing out by putting the content into two grids, the height of the content grew by about  25% and looked really imbalanced on some of the items.  So I instead replaced the and/or with the stacked font awesome icon and a tried out a small line seperator design to give it a bit more focus

**Comment by LMElston** [comment]
I took a stab at separating the "and" items and simplifying the rest of the language where I thought there was an opportunity.

[Before you start.docx](https://github.com/gc-proto/covid-19-guidance/files/5198137/Before.you.start.docx)

**Comment by LMElston** [comment]
> @lbelmore-gc @LMElston I have updated the checklist items for the calculate page. After testing out by putting the content into two grids, the height of the content grew by about 25% and looked really imbalanced on some of the items. So I instead replaced the and/or with the stacked font awesome icon and a tried out a small line seperator design to give it a bit more focus

I like the redesign and have a feeling it will help enough with the visibility of the second "and" item that separating them out is probably not necessary. I can re-word my document accordingly, I just need to wait until tomorrow morning to do it.

**Comment by LMElston** [comment]
@Christopher-O Here's a second round that just tidies up the existing language without making the "and" items into separate checks.
[Before you start_r1.docx](https://github.com/gc-proto/covid-19-guidance/files/5201550/Before.you.start_r1.docx)

**Comment by Christopher-O** [comment]
@LMElston is it okay to keep the "Both of the following apply"?  I know the "and" wasn't as of an issue as the or but I find that gives balance to the multiple scenario design.   Also, for the EI, QPIP, CPP and QPP...could it be considered confusing that the QPIP is only for Quebec (and does not have any significance for outside of Quebec), and the QPP is the alternative to the CPP not in addition to, therefore someone could not calculate both..it's one or the other depending if you live in Quebec or not.  I'm worried for a small new business owner in BC thinking "oh I didn't know I had to calculate a QPIP....I guess I don't qualify then"...not knowing it's for Quebec only.

**Comment by LMElston** [comment]
Both of the following apply is fine.

The and/and/and/or was confusing because it said 'EI and QPIP' but 'CPP or QPP' (for consistency, we should either say "EI or QPIP and CPP or QPP" or "EI and CPP or QPIP and QPP"). Technically it's possible for an employee to have moved from/to Quebec and have both (but very unlikely). I feel like the commas are easier to deal with than the ands/ors and people are familiar enough with this that it's not going to throw people off (or they can read about it if they need to) but it's not a hill I'm willing to die on either :)

**Comment by Christopher-O** [comment]
@LMElston could we enhance the overlay text to include the phrase "- for Quebec employees only" for both the QPIP and the QPP.  I know they have the phrase Quebec in them, but I could see a new (maybe newly immigrated) business owner be confused on why they might need to calculate something that has the phrase Quebec in it...as well as if they were in Quebec, it doesn't apply to their employees who live outside of Quebec.

**Comment by LMElston** [comment]
@Christopher-O I thought about the Quebec thing and I think there is enough information out there for people to be able to navigate this without spelling it out (if you're so new to employment that you don't know what QPIP/QPP are you're probably reading other stuff before this). Residency/location is slightly complex in terms of whether you deduct EI/QPIP or both. I suggest we keep an eye on feedback and adapt if we need to.

@lbelmore-gc the translation for this section is attached under issue #82.

**Comment by tanyafowler** [comment]
Part of PubHub ticket 208575 - assigned to Mathieu.
