### ISSUE TITLE
Clarify reporting of CEWS on tax returns

### ISSUE THREAD

**Issue by LMElston** [gc-proto/covid-19-guidance#94]
From David O'Horan via email. Wrote back to David to ask for a description of what the issue is so we can adjust the content appropriately. Given the wide context of 'after' used on the After you apply page I think it's important to mention that this focuses on the task of reporting the income at tax time, specifically clarifying information for employers and individuals. Will follow up with Mike/Manon.

**Comment by LMElston** [comment]
From the program support log, via Mike Joy (email):

The Government has announced the eligible claims periods from March 15 until November 21, 2020, but the required reporting period on T4 slip is Mar 15 to Sep 26, 2020.

The employment income of CEWS amounts will be reported on employee’s T4 slip at the year end, or upon filing. In addition, to report these CEWS related employment income on box 14, 4 new Other Information codes will be used to have the employment income paid during this period be reported on T4 slip precisely in order to allow CRA make the validations to perform the necessary compliance enforcement in the future.

The T4 return will continually only allow 6 Other Information codes to be provided on each slip. 

We are introducing 4 new Other Information codes on the T4 as follows:

•	Code 57:
o	Employment income – March 15 to May 9
o	Revenus d'emploi – 15 mars au 9 mai

•	Code 58: 
o	Employment income – May 10 to July 4
o	Revenus d'emploi – 10 mai au 4 juillet

•	Code 59: 
o	Employment income – July 5 to August 29
o	Revenus d'emploi – 5 juillet au 29 août

•	Code 60: 
o	Employment income – August 30 to September 26
o	Revenus d'emploi – 30 août au 26 septembre

**Comment by lbelmore-gc** [comment]
Adding in the details from Sara's email:

Looks like the Canadian Payroll Association has flagged that some of the content on the CEWS pages is out of date. Not sure if this was part of the updates you and your team are already working on but if not, can you look into updating the content to include the details on the reporting codes? 
They are currently available on the support for employers web page: https://www.canada.ca/en/revenue-agency/campaigns/covid-19-update/support-employers-cra-covid-19.html

**Comment by tanyafowler** [comment]
Since the content is already posted on the Information for employers page (COVID campaign) - https://www.canada.ca/en/revenue-agency/campaigns/covid-19-update/support-employers-cra-covid-19.html - have added link to this page on the After you apply > Include the subsidy on your returns section. 

https://www.canada.ca/en/revenue-agency/services/subsidy/emergency-wage-subsidy/cews-after-apply.html#h-2 

Submitted PubHub ticket 210073 - ticket was returned for review, approved for publishing, and updates are now live.
